name: 'Get Release Tags'
description: 'Gets the latest release tags from the repository'

outputs:
  tags:
    description: 'JSON array of release tags'
    value: ${{ steps.get-tags.outputs.tags }}

runs:
  using: composite
  steps:
    - id: get-tags
      shell: bash
      run: |
        # Get all tags sorted by version
        TAGS=$(git tag --sort=-v:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -10)
        
        # Convert to JSON array
        JSON_TAGS="["
        while IFS= read -r tag; do
          if [ -n "$tag" ]; then
            if [ "$JSON_TAGS" != "[" ]; then
              JSON_TAGS="$JSON_TAGS,"
            fi
            JSON_TAGS="$JSON_TAGS\"$tag\""
          fi
        done <<< "$TAGS"
        JSON_TAGS="$JSON_TAGS]"
        
        echo "tags=$JSON_TAGS" >> $GITHUB_OUTPUT 