name: Update Release Tags
on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch: # Allow manual trigger

jobs:
  update-tags:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get tags and update workflow
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get all tags sorted by version
          TAGS=$(git tag --sort=-v:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -10)
          
          # Create options array
          OPTIONS=""
          while IFS= read -r tag; do
            OPTIONS="$OPTIONS          - $tag\n"
          done <<< "$TAGS"
          
          # Update the workflow file
          sed -i "/base_version:/,/type:/ c\      base_version:\n        description: 'Base version for hotfix'\n        required: false\n        type: choice\n        options:\n$OPTIONS" .github/workflows/release-process.yml
          
          # Check if there are changes
          if git diff --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          
          # Commit and push changes
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git remote set-url origin "https://${GITHUB_ACTOR}:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git add .github/workflows/release-process.yml
          git commit -m "chore: Update release tags list"
          git push 